<a href="https://colab.research.google.com/github/boazgajja/-Realtime-Ecommerce-Data-Pipeline-Analaytics-Dashboard/blob/main/feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#first question
import numpy as np
n_elements = 10
data_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

avg_value = np.mean(data_vector)

sample_var = np.var(data_vector, ddof=1)

population_var = np.var(data_vector)

print(f'Data Vector (1x{n_elements}): {data_vector}')
print(f'Calculated Mean: {avg_value:.4f}')
print(f'Sample Variance: {sample_var:.4f}')
print(f'Population Variance: {population_var:.4f}')



Data Vector (1x10): [ 1  2  3  4  5  6  7  8  9 10]
Calculated Mean: 5.5000
Sample Variance: 9.1667
Population Variance: 8.2500


In [4]:
#second question
import numpy as np

num_elements = 10
data_x = np.array([12, 5, 9, 18, 22, 35, 44, 28, 13, 17])
data_y = np.array([14, 7, 11, 20, 25, 38, 42, 30, 16, 19])

avg_x = np.mean(data_x)
avg_y = np.mean(data_y)

cov_xy = np.sum((data_x - avg_x) * (data_y - avg_y)) / (num_elements - 1)

print(f'Data X (1x{num_elements} array): {data_x}')
print(f'Data Y (1x{num_elements} array): {data_y}')
print(f'Calculated Covariance: {cov_xy:.4f}')


Data X (1x10 array): [12  5  9 18 22 35 44 28 13 17]
Data Y (1x10 array): [14  7 11 20 25 38 42 30 16 19]
Calculated Covariance: 139.3778


In [6]:
#third question
import numpy as np

num_items = 10
data_x = np.array([10, 12, 18, 22, 29, 33, 37, 41, 25, 19])
data_y = np.array([8, 11, 17, 23, 28, 32, 35, 39, 22, 16])

avg_x = np.mean(data_x)
avg_y = np.mean(data_y)

cov_xy = np.sum((data_x - avg_x) * (data_y - avg_y)) / (num_items - 1)

var_x = np.var(data_x, ddof=1)
var_y = np.var(data_y, ddof=1)

corr_xy = cov_xy / np.sqrt(var_x * var_y)

print(f'Data X (1x{num_items} array): {data_x}')
print(f'Data Y (1x{num_items} array): {data_y}')
print(f'Correlation Coefficient: {corr_xy:.4f}')


Data X (1x10 array): [10 12 18 22 29 33 37 41 25 19]
Data Y (1x10 array): [ 8 11 17 23 28 32 35 39 22 16]
Correlation Coefficient: 0.9935


In [7]:
import numpy as np

# Define dimensions
num_rows = 4
num_cols = 5

# Define the matrix
data_matrix = np.array([
    [1.2, 3.5, 5.7, 2.1, 4.4],
    [6.8, 2.4, 3.6, 8.7, 5.9],
    [4.3, 7.1, 8.2, 1.4, 3.7],
    [9.8, 2.1, 4.5, 6.2, 7.0]
])

# Compute the transpose of the matrix
transposed_matrix = data_matrix.T

# Compute the covariance matrix
covariance_matrix = np.cov(transposed_matrix, rowvar=False)

# Compute the correlation matrix
correlation_matrix = np.corrcoef(transposed_matrix, rowvar=False)

# Print the results
print(f'Data Matrix ({num_rows}x{num_cols} dimension):\n{data_matrix}\n')
print(f'Covariance Matrix ({num_rows}x{num_rows} dimension):\n{covariance_matrix}\n')
print(f'Correlation Matrix ({num_rows}x{num_rows} dimension):\n{correlation_matrix}\n')


Data Matrix (4x5 dimension):
[[1.2 3.5 5.7 2.1 4.4]
 [6.8 2.4 3.6 8.7 5.9]
 [4.3 7.1 8.2 1.4 3.7]
 [9.8 2.1 4.5 6.2 7. ]]

Covariance Matrix (4x4 dimension):
[[ 3.207  -2.8255  3.121  -2.867 ]
 [-2.8255  6.327  -6.3865  5.228 ]
 [ 3.121  -6.3865  7.443  -4.4235]
 [-2.867   5.228  -4.4235  8.227 ]]

Correlation Matrix (4x4 dimension):
[[ 1.         -0.62725902  0.6388079  -0.5581584 ]
 [-0.62725902  1.         -0.93065773  0.72462934]
 [ 0.6388079  -0.93065773  1.         -0.56528996]
 [-0.5581584   0.72462934 -0.56528996  1.        ]]

